version: "3.8"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:80"
    networks:
      - mi-red
    depends_on:
      - db
    restart: 'on-failure:15'
  db:
    image: mariadb:latest
    container_name: db
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=testdb
    networks:
     - mi-red
    restart: 'on-failure:15'
networks:
 mi-red: